name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"
      - "src/app/api/**"

jobs:
  build:
    name: build-next-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run install && npm run  build
