name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "src/app/upper/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
